[package]
name = "tilemap-sandbox"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
ahash = "0.8"
godot = "0.1"
image = "0.25"
image-atlas = "0.4"
rand = "0.8"
rstar = "0.12"
slab = "0.4"
