[package]
name = "tilemap-sandbox"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
ahash = "0.8"
ecs-tiny = "0.1"
enum_dispatch = "0.3"
godot = { git = "https://github.com/godot-rust/gdext" }
image = "0.25"
image-atlas = "0.4"
rand = "0.8"
rstar = "0.12"
slab = "0.4"
