[package]
name = "native-main"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
ahash = "0.8"
glam = "0.28"
godot = "0.2"
native-core = { path = "../native-core" }
rand = "0.8"
